# Generated by Django 5.2.14 on 2026-05-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="emp_id",
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
